server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/auth/**
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/products/**
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/order/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
