server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url:  jdbc:mysql://localhost:3306/dressklub_userdb
    username: root
    password: rinshad3657
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true