server:
  port: 8084

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/dressklub_orderdb
    username: root
    password: rinshad3657
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      productService:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000